name: Start FoD scan

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.0
        with:
          vs-version: 10.0
      - uses: actions/setup-java@v1     # Required for ScanCentral Client and FoD Uploader
        with:
          java-version: 1.8
      - uses: fortify-actions/setup-scancentral-client@v1
      - uses: fortify-actions/setup-fod-uploader@v1
      - run: scancentral package -bt msbuild -bf WebGoat.NET.sln -o package.zip
      - run: java -jar "$Env:FOD_UPLOAD_JAR" -z package.zip -aurl https://api.ams.fortify.com/ -purl https://ams.fotify.com/ -rid "$Env:FOD_RELEASE_ID" -tc "$Env:FOD_TENANT" -uc "$Env:FOD_USER" "$Env:FOD_PAT" -ep 2 -pp 1
        env: 
          FOD_TENANT: ${{ secrets.FOD_TENANT }}  
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PAT: ${{ secrets.FOD_PAT }}
          FOD_RELEASE_ID: ${{ secrets.FOD_RELEASE_ID }}  
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: scancentral-logs
          path: C:/Users/runneradmin/AppData/Local/Fortify/scancentral/log # Any way we can reference %LOCALAPPDATA%
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: package.zip
          path: package.zip
